### ISSUE TITLE
Crash When Open Invertory

### ISSUE THREAD

**Issue by Cactusstudent** [ThinkingStudios/MiniHUD-Forge#1]
https://mclo.gs/xctWq64
https://mclo.gs/FKT4toK （latest.log）
就……挺突然，开了个物品栏就寄了（虽然确实是Pre版）
游戏版本：1.18.2 Forge
Forge版本：40.2.4
其余模组：Mafglib 0.1.4

**Comment by TexBlock** [comment]
此崩溃与MaFgLib有关（[ThinkingStudios/MaLiLib-Forge issue#5](https://github.com/ThinkingStudios/MaLiLib-Forge/issues/5)），正在修复。

**Comment by TexBlock** [comment]
[MaFgLib 0.1.4fix-mc1.18.2](https://modrinth.com/mod/mafglib/version/0.1.4fix-mc1.18.2)
