### ISSUE TITLE
Crash when install EMI

### ISSUE THREAD

**Issue by PeakXing** [ThinkingStudios/MiniHUD-Forge#12]
[latest.log](https://github.com/ThinkingStudios/MiniHUD-Forge/files/14587414/latest.log)
When I install EMI at the same time, it crashes when starting the client.

**Comment by TexBlock** [comment]
BoccHUD mixin the ItemStack[[this](https://github.com/ThinkingStudios/MiniHUD-Forge/blob/1.20.x-forge/dev/src/main/java/fi/dy/masa/minihud/mixin/MixinItemStack.java)], but EMI also mixin the ItemStack [[this](https://github.com/emilyploszaj/emi/blob/1.20/xplat/src/main/java/dev/emi/emi/mixin/ItemStackMixin.java)] (they both mixin the same method), resulting in a mixin conflict between the two mods

**Comment by TexBlock** [comment]
non-replicable
