### ISSUE TITLE
孤独HUD在mc1.19报错

### ISSUE THREAD

**Issue by 204848** [ThinkingStudios/MiniHUD-Forge#15]
你好，我在mc1.19，forge41.1.0，MaFgLib0.1.12，孤独HUD0.1.6的情况下报错，日志是下面这个
[错误报告-2024-6-10_星期一_6.55.47.zip](https://github.com/user-attachments/files/15754504/-2024-6-10_._6.55.47.zip)
.zip](https://github.com/user-attachments/files/15754503/-2024-6-10_._6.55.47.zip)
启动器报错窗口为
![屏幕截图 2024-06-10 072306](https://github.com/ThinkingStudios/MiniHUD-Forge/assets/143565148/63a6785a-c563-453d-a10a-ec3d77b76e0d)
麻烦您看一下，我只装了如下mod
![image](https://github.com/ThinkingStudios/MiniHUD-Forge/assets/143565148/125943b5-1ed1-483d-8141-4c03686b33ef)

**Comment by TexBlock** [comment]
请将游戏更新到1.19.2版本，1.19版本已不受支持
