### ISSUE TITLE
BoccHUD + MaFgLib crash on startup 1.20.6

### ISSUE THREAD

**Issue by PixelKing99** [ThinkingStudios/MiniHUD-Forge#18]
MaFgLib didnt cause any issues on its own but after adding BoccHUD it crashes on startup

i think this is the important part of the crash report but ill put the whole thing aswell

> Description: Initializing game
> 
> java.lang.NullPointerException: Cannot invoke "net.neoforged.neoforge.network.registration.PayloadRegistrar.playToServer(net.minecraft.network.protocol.common.custom.CustomPacketPayload$Type, net.minecraft.network.codec.StreamCodec, net.neoforged.neoforge.network.handling.IPayloadHandler)" because the return value of "org.thinkingstudio.mafglib.util.NeoNetwork.getPayloadRegistrar()" is null
> 	at TRANSFORMER/mafglib@0.1.10-mc1.20.6/fi.dy.masa.malilib.network.IPluginClientPlayHandler.registerPlayPayload(IPluginClientPlayHandler.java:80) ~[MaFgLib-0.1.10-mc1.20.6.jar%23188!/:?] {re:classloading}

[crash-2024-07-06_17.20.02-client.txt](https://github.com/user-attachments/files/16117649/crash-2024-07-06_17.20.02-client.txt)

BoccHUD-0.1.2-mc1.20.6
MaFgLib-0.1.10-mc1.20.6
NeoForge 20.6.119

**Comment by TexBlock** [comment]
fix in mafglib
