### ISSUE TITLE
My BoccHUD-0.1.7 still crashes with embeddium

### ISSUE THREAD

**Issue by EhabWilson** [ThinkingStudios/MiniHUD-Forge#19]
MC version: 1.18.2
BoccHUD: 0.1.7
embeddium: 0.3.x (试过目前所有的release)

可以打开游戏初始菜单，但进入世界过程中崩溃
报错：
[crash-2024-07-12_20.17.33-client.txt](https://github.com/user-attachments/files/16193975/crash-2024-07-12_20.17.33-client.txt)

**Comment by TexBlock** [comment]
升级你的Forge到最新版本
