### ISSUE TITLE
Light level missing number

### ISSUE THREAD

**Issue by shouxd** [ThinkingStudios/MiniHUD-Forge#23]
Same as in #10 but happening in both version 0.1.8 and 0.1.9, MC 1.21.1.

light_level_numbers.png is present in both .jar, but not working for some reason.

**Comment by ghost** [comment]
[20:00:36] [Render thread/WARN] [minecraft/TextureManager]: Failed to load texture: minihud:textures/misc/light_level_numbers.png

is the error i got

 i took the resource pack from the #10 and if you rename the dir bocchud to minihud it will work
