### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Mccandycube6623** [ThinkingStudios/MiniHUD-Forge#3]
[crash-2023-06-22_07.16.50-fml.txt](https://github.com/ThinkingStudios/MiniHUD-Forge/files/11880727/crash-2023-06-22_07.16.50-fml.txt)
1.18.2

**Comment by TexBlock** [comment]
You should download the latest version of MaFgLib, the other malilib forge ports are missing some features compared to mafglib.

你应该下载MaFgLib的最新版，其他malilib的forge移植版和mafglib相比缺失了部分功能。
