### ISSUE TITLE
打开水面调试信息（WaterEnabled）

### ISSUE THREAD

**Issue by zaychik0019** [ThinkingStudios/MiniHUD-Forge#4]
打开水面调试信息立马崩溃然后就再也打不开了，删除mod和前置重新下载后打开也是崩溃。之前和其他mod，光影并没有发生冲突，就是碰了一下这个发生的。
[错误报告-2023-7-31_3.12.00.zip](https://github.com/ThinkingStudios/MiniHUD-Forge/files/12209921/-2023-7-31_3.12.00.zip)

**Comment by Kasualix** [comment]
建议卸载OptiNOTFine。

**Comment by zaychik0019** [comment]
确实好了，谢谢
