### ISSUE TITLE
[1.19.2] 与夸克一起装后注入失败

### ISSUE THREAD

**Issue by qznfbnj** [ThinkingStudios/MiniHUD-Forge#6]
似乎与夸克一起装后，游戏内模组计数不能超过22个？不然就会 Mixin apply failed
完全不懂Mixin，连问题在哪都镐不清楚
[debug.log](https://gist.github.com/qznfbnj/72580a3998a8b0ea482e335a47e9b46c#file-debug-log)
## 模组列表
![image](https://github.com/ThinkingStudios/MiniHUD-Forge/assets/100760086/5d95562e-278a-4e01-bb6a-6ecec375b370)

**Comment by qznfbnj** [comment]
好吧，至少在 minihud.mixins.json 中注释掉 MixinItemStack 就没问题了

**Comment by TexBlock** [comment]
在不安装夸克的情况下会有这个问题吗

**Comment by qznfbnj** [comment]
奇怪，450个模组反而没问题了，看来问题找错了。下午再回来测试
![image](https://github.com/ThinkingStudios/MiniHUD-Forge/assets/100760086/0e7aa829-59bd-48b7-a80b-20a26e98325d)
按一楼图放好模组，还是崩溃，搞不明白
